### ISSUE TITLE
Script not working, alway return cannot connect to auth service

### ISSUE THREAD

**Issue by wrathdev** [ashutoshvarma/scripts#1]
I tried many times using different devices and randomizing my MAC but script always return same error.
`ERROR: Unable to access auth service`
But I was able to login through the browser successful so the problem lies in script.

**Comment by ashutoshvarma** [comment]
I can reproduce what you stated on my machine and probably find a fix for that.

**Comment by ashutoshvarma** [comment]
Well we are passing POST data in JSON format and apparently using `"Content-Type": "application/x-www-form-urlencoded"` urlencoded headers.
Even with that it should not deny the request as almost all the APIs handle json and urlencoded as same.

**Comment by ashutoshvarma** [comment]
Well I looked into how login portal handle ajax POST request to server end and found that they use urlencoded form data.  So the fix should be changing the payload to urlencoded as it look likes json data is not handled by server.
Also weird thing is that it was working yesterday with JSON POST data.
